name: KetchupAI

on: [pull_request, issues]

jobs:
  greeting:Hello,I am Ketchup the artificial intellingence robot 
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:Greet
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Message that will be displayed on users first issue'"Hello there"
        pr-message: 'Message that will be displayed on users first pull request'
